### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by tasaif** [panyam/astgen#1]
I'm not sure what this library is but it's being pulled in as a dependency for another library. Can you help me?

Installation source: python-3.6.5-embed-win32.zip

PS C:\Users\tasaif\repo\gmrexc\gmrexc\client> python --version
Python 3.6.5

PS C:\Users\tasaif\repo\gmrexc\gmrexc\client>  pip --no-cache-dir install astgen
Collecting astgen
  Downloading https://files.pythonhosted.org/packages/41/10/932497daee137dd4b71950d902062c83a655908a61e6e907008105fee682/astgen-0.1.6.12.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\tasaif\AppData\Local\Temp\pip-install-1in84_6d\astgen\setup.py", line 79
        print "PDIR: ", pdir(), os.listdir(pdir())
                     ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\tasaif\AppData\Local\Temp\pip-install-1in84_6d\astgen\

**Comment by panyam** [comment]
> I'm not sure what this library is but it's being pulled in as a dependency for another library. Can you help me?
> 
> Installation source: python-3.6.5-embed-win32.zip
> 
> PS C:\Users\tasaif\repo\gmrexc\gmrexc\client> python --version
> Python 3.6.5
> 
> PS C:\Users\tasaif\repo\gmrexc\gmrexc\client> pip --no-cache-dir install astgen
> Collecting astgen
> Downloading https://files.pythonhosted.org/packages/41/10/932497daee137dd4b71950d902062c83a655908a61e6e907008105fee682/astgen-0.1.6.12.tar.gz
> Complete output from command python setup.py egg_info:
> Traceback (most recent call last):
> File "", line 1, in 
> File "C:\Users\tasaif\AppData\Local\Temp\pip-install-1in84_6d\astgen\setup.py", line 79
> print "PDIR: ", pdir(), os.listdir(pdir())
> ^
> SyntaxError: invalid syntax
> 
> ```
> ----------------------------------------
> ```
> Command "python setup.py egg_info" failed with error code 1 in C:\Users\tasaif\AppData\Local\Temp\pip-install-1in84_6d\astgen\

Hey mate, this is a really old library for building Abstract Syntax Trees in parser development and is written in python 2.x.   This is not compatible with python 3.  But let me do a quick fix to see what is using this.

**Comment by panyam** [comment]
Ive updated print to be used in the new py3.x way so this should be good to go ahead.   Do you know what this is being used in?  Can you let me know?

**Comment by tasaif** [comment]
Thanks. I believe it was a websocket library.

**Comment by panyam** [comment]
Cool.  Is this issue still blocking?

**Comment by tasaif** [comment]
No, the issue was resolved by using the full installation of Python then packaging it up as opposed to trying to use the "embedded" version of python for Windows.

Maybe the full installation uses a pickled version of this or something? In any case, thanks for looking into it.
